export const FETCH_INGREDIENTS = "FETCH_INGREDIENTS";
export const FETCH_RECIPES = "FETCH_RECIPES";
export const FETCH_MORE_RECIPES = "FETCH_MORE_RECIPES";
export const ADD_ITEM = "ADD_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const TOGGLE_COMPLEX = "TOGGLE_COMPLEX"
